from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
from . import views

urlpatterns = [
    path('',views.index,name="index"),
    path('adminsite/', views.admin_dashboard, name='admin_dashboard'),
    path('registeruser/',views.registeruser, name="registeruser"),
    path('userlogin/',views.login_view, name="userlogin"),
    path('manageuser/',views.manageuser,name="manageuser"),
    path('deleteuser/<int:uid>',views.deleteuser,name="deleteuser"),
    path('edituser/<int:uid>',views.edituser,name="edituser"),
    path('adduser/',views.adduser,name='adduser'),
    path('addbrand/',views.addbrand,name="addbrand"),
    path('managebrand/',views.managebrand,name="managebrand"),
    path('deletebrand/<int:bid>',views.deletebrand,name="deletebrand"),
    path('editbrand/<int:id>',views.editbrand,name="editbrand"),
    path('addcategory/',views.addcategory,name="addcategory"),
    path('managecategory/',views.managecategory,name="managecategory"),
    path('deletecategory/<int:cid>',views.deletecategory,name="deletecategory"),
    path('editcategory/<int:cid>',views.editcategory,name="editcategory"),
    path('addproduct/',views.addproduct,name="addproduct"),
    path('manageproduct/',views.manageproduct,name="manageproduct"),
    path('editproduct/<int:id>/', views.editproduct, name='editproduct'),
    path('product/<int:pid>/', views.product_details, name='product_details'),
    path('add-review/<int:pid>/', views.add_review, name='add_review'),
    path('deleteproduct/<int:pid>',views.deleteproduct,name="deleteproduct"),
    path('addtocart/<int:pid>/', views.addtocart, name='addtocart'),
    path('wishlist/add/<int:pid>/', views.add_to_wishlist, name='add_to_wishlist'),
    path('wishlist/', views.wishlist, name='wishlist'),
    path('remove-wishlist/<int:wid>/', views.remove_wishlist, name='remove_wishlist'),
    path('cart/', views.cart, name='cart'),
    path('removecart/<int:cid>/', views.removecart, name='removecart'),
    path('logout/', views.logout_view, name='logout'),
    path('increase/<int:cid>/', views.increase_quantity, name='increase_quantity'),
    path('decrease/<int:cid>/', views.decrease_quantity, name='decrease_quantity'),
    path('place-order/', views.place_order, name='place_order'),
    path('my-orders/', views.my_orders, name='my_orders'),
    path('my-profile/', views.my_profile, name='my_profile'),
    path('edit-profile/', views.edit_profile, name='edit_profile'),
    path('change_password/', views.change_password, name='change_password'),
    path('delete-review/<int:rid>/', views.delete_review, name='delete_review'),
    path('edit-review/<int:rid>/', views.edit_review, name='edit_review'),
    path("payment/", views.payment, name="payment"),
    path('invoice/<int:order_id>/', views.download_invoice, name='download_invoice'),
    path('order-details/<int:order_id>/', views.order_details, name='order_details'),
    path('cancel-order/<int:order_id>/', views.cancel_order, name='cancel_order'),
    path("admin-dashboard/", views.admin_dashboard, name="admin_dashboard"),
    path("managepayment/", views.managepayment, name="managepayment",), 
    path("managereview/", views.managereview, name="managereview"),
    path("deletereview/<int:rid>/",views.deletereview,name="deletereview"),   
    path("manageorder/",views.manageorder,name="manageorder"),
    path("updateorder/<int:oid>/",views.updateorder,name="updateorder"),
    path("deleteorder/<int:oid>/",views.deleteorder,name="deleteorder",),
    path("reports/", views.reports, name="reports"),
    path('export-report-pdf/', views.export_report_pdf, name='export_report_pdf'),
    path("export-report-excel/", views.export_report_excel, name="export_report_excel"),
    

]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)