# Generated by Django 5.2.1 on 2025-06-30 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fashionapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='bramd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='brand_photo/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
