# Generated by Django 5.2.1 on 2025-06-30 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fashionapp', '0002_bramd'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='bramd',
            new_name='brand',
        ),
    ]
