# Generated by Django 6.0.6 on 2026-07-04 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fashionapp', '0008_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregister',
            name='profile_image',
            field=models.ImageField(default='profile/default.png', upload_to='profile/'),
        ),
    ]
