# Generated by Django 6.0.6 on 2026-07-04 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fashionapp', '0009_userregister_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregister',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile/'),
        ),
    ]
