# Generated by Django 6.0.6 on 2026-07-29 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fashionapp', '0015_product_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregister',
            name='profile_image',
            field=models.ImageField(blank=True, default='profile/default-user.png', null=True, upload_to='profile/'),
        ),
    ]
